version: '3.7'

services:

  api:
    build:
      context: ./server
      dockerfile: app.dockerfile
    entrypoint: ['/app/server/scripts/start.sh']
    volumes:
      - .:/app
    ports:
      - 5000:80 # local:remote
    environment:
      - FLASK_APP=server/app:app
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL_DEV=postgresql://postgres:postgres@db:5432/api_dev
      - DATABASE_URL_TEST=postgresql://postgres:postgres@db:5432/api_test
    depends_on:
      - db
    restart: always

  db:
    build:
      context: ./server
      dockerfile: db.dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}